### ISSUE TITLE
请问这份代码在实际生产中应用过吗？？？

### ISSUE THREAD

**Issue by NullPointerHub** [rockcarry/ffrdp#1]

**Comment by rockcarry** [comment]
已经用过，做音视频传输

**Comment by NullPointerHub** [comment]
为什么，我在启用FEC的时候，设置了链路的丢包率，传输的一个315.8MB的视屏文件，接收的不完整呢？

**Comment by rockcarry** [comment]
不启用FEC就正常？

**Comment by NullPointerHub** [comment]
还在测试，我主要想做做FEC这一块，可以加个qq吗？？？
qq:1531653614

**Comment by rockcarry** [comment]
ffrdp 的 FEC 目前功能比较弱，我实测弱网环境下的性能提升并不大。
这个代码本身已经非常简单了，就500行，有问题设个断电，花点时间调试下就可以解决了。
你可以加 fanplayer 的那个群。383930765
ffrdp 的实用例子，你可以参考 livedesk 和 fanplayer 项目。实测实时音视频传输都很正常。

**Comment by NullPointerHub** [comment]
好的，谢谢！
