### ISSUE TITLE
发送数据时候，为什么这么定义？？

### ISSUE THREAD

**Issue by NullPointerHub** [rockcarry/ffrdp#2]
*(uint32_t *) (sendbuf + 4) = Get_Tick_Count();
strcpy((char *) sendbuf + 8, "rockcarry server data");

sendbuf前4个字节为什么没有使用，还有4-8字节，时间戳什么作用？？？

**Comment by rockcarry** [comment]
那只是一个测试程序，sendbuf 里面随便放什么都可以，前 4个字节我之前应该是放的 buf size。
