### ISSUE TITLE
请问下这个test的demo

### ISSUE THREAD

**Issue by czk630597526** [rockcarry/ffrdp#3]
这个demo运行不了吧，send需要先connect上，connect需要先收到数据包，这是什么意思
我编译后运行test --server=192.168.3.5:10086 --client=192.168.3.5:10088，全部都在报错，需要怎么样才能运行吗

**Comment by rockcarry** [comment]
--server=192.168.3.5:10086 --client=192.168.3.5:10086
 用这个参数，含义为 server 监听 10086 端口，client 连接到 10086 端口，然后进行数据收发

这个 demo 肯定是没问题的，我们已经用到项目中了的。

更多的测试，你可以试下 LiveDesk 作为服务器，fanplayer 作为播放器，可以远程监控 LiveDesk 的 windows 桌面

**Comment by czk630597526** [comment]
ok，是我这里有点问题，已经测试过，打算好好学习下这部分，谢谢，以后希望还能请教
