### ISSUE TITLE
关于ffrdp_update的问题

### ISSUE THREAD

**Issue by tyc1998** [rockcarry/ffrdp#4]
该函数中srcaddr好像没有未初始化就使用了，而且dstaddr为指针，srcaddr为变量，我对此有一些疑惑，望解答

**Comment by rockcarry** [comment]
srcadd 是 recvfrom 初始化的，获取到的是对方的地址
dstaddr 是指针指向了要用到的目的地址

**Comment by tyc1998** [comment]
好像看书没仔细，我再好好研究一下。老哥把群申请通过一下呗
